name: Get Unity license activation file ğŸ”

on: workflow_dispatch

jobs:
  #  requestManualActivationFile:
  #    name: Request activation âœ”
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: game-ci/unity-activate@v2
  #
  #  activateAndThenReturnLicense:
  #    name: returnLicense ğŸˆ
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2
  #      - uses: game-ci/unity-activate@v2
  #      - uses: game-ci/unity-return-license@v2
  requestManualActivationFile:
    name: Request manual activation file ğŸ”‘
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: game-ci/unity-request-activation-file@v4
        id: getManualLicenseFile

      - uses: actions/upload-artifact@v4
        with:
          name: Manual Activation File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}